project: 
  type: website
website: 
  title: "INFS649-DigitalCuration"
  site-url: "https://zackbatist.info/INFS649-DigitalCuration/" 
  repo-url: "https://github.com/zackbatist/INFS649-DigitalCuration"
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: false
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left:
      - text: "CC0"
        href: https://creativecommons.org/publicdomain/zero/1.0/
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo]
    code-copy: true
    code-overflow: wrap
    toc: true
